name: Publish Common JWT Interceptor Module

on:
  push:
    branches:
      - main
    paths:
      - 'common-modules/common-jwt-interceptor/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action@master
        with:
          args:
            pack
        env:
          WORKING_DIR: 'common-modules/common-jwt-interceptor'

      - name: Ballerina Push
        uses: ballerina-platform/ballerina-action@master
        with:
          args:
            push
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BallerinaToken }}
          WORKING_DIR: 'common-modules/common-jwt-interceptor'
